### ISSUE TITLE
Twig string interpolation

### ISSUE THREAD

**Issue by ben-rogerson** [JungleMinds/JM_Basic-Twig-Project#2]
Nice starter you've put together.
I'm having trouble getting twig string interpolation to work correctly.

Is this a feature that could be added?

{{ "this is a string #{ andAVariable }" }}

**Comment by Rilliano** [comment]
@ben-rogerson Would this help:

{{ "this is a string "  ~ andAVariable }}

**Comment by grumpyoldman-io** [comment]
@ben-rogerson we use the [twig-loader package](https://www.npmjs.com/package/twig-loader), which uses the [twig.js](https://github.com/twigjs/twig.js) package. There you can see that this is a requested feature that has a ready label on it: https://github.com/twigjs/twig.js/issues/277. I hope you can get by with @Rilliano's suggestion

**Comment by ben-rogerson** [comment]
@Rilliano I ended up adjusting all of my components to remove the string variables. @grumpyoldman-io Seems like a limitation of twig.js that isn't getting fixed anytime soon. Are there any other limitations that you can think of?

**Comment by grumpyoldman-io** [comment]
@ben-rogerson I've had some troubles with importing other twig files inside a twig file using twig.js. It had to do with it resolving relative paths differently. Apart from that I haven't seen any major hurdles.

**Comment by grumpyoldman-io** [comment]
@ben-rogerson If you have any more questions feel free to ask, but for now I will close this issue.
